version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"   
      - "5672:5672"     
    networks:
      - rabbitnet

  # Microservice producteur 
  producer:
    build: ./producer
    container_name: producer
    depends_on:
      - rabbitmq
    networks:
      - rabbitnet

  # Microservice front (Node) jouant le rôle de consommateur
  front:
    build: ./front
    container_name: front
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"
    networks:
      - rabbitnet

networks:
  rabbitnet:
    driver: bridge
